# Generated by Django 3.2.5 on 2021-11-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('CLIENTE', 'Cliente'), ('SECRETARIA', 'Secretaria'), ('CAJERA', 'Cajera'), ('EMP_MARKETING', 'Empleado Marketing'), ('JE_COMER', 'Jefe Comercialización'), ('JE_ADM', 'Jefe Administración'), ('GERENTE', 'Gerente'), ('AGENTE_INMOBILIARIO', 'Agente Inmobiliario')], default='CLIENTE', max_length=50, verbose_name='Tipo'),
        ),
    ]
