# Generated by Django 3.2.5 on 2021-11-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_agente_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
