# Generated by Django 3.2.5 on 2021-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_turno_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.CharField(max_length=255),
        ),
    ]
